import React from 'react';

export default function BookingSection() {
  return (
      <section
            id="book"
                  className="py-24 px-6 text-center"
                        style={{ background: 'linear-gradient(135deg, rgba(139,60,247,0.08) 0%, rgba(13,148,136,0.04) 100%)' }}
                            >
                                  <div className="max-w-2xl mx-auto">
                                          <p className="text-xs tracking-widest uppercase mb-4 font-semibold" style={{ color: '#14b8a6' }}>
                                                    Book Now
                                                            </p>
                                                                    <h2 className="font-black mb-6" style={{ fontSize: 'clamp(32px,5vw,56px)', color: '#f0eaf8' }}>
                                                                              Begin Your Transformation
                                                                                      </h2>
                                                                                              <hr className="divider-brand" />
                                                                                                      <p className="text-lg leading-relaxed mt-6 mb-10" style={{ color: '#a9a3b8' }}>
                                                                                                                Book your appointment at the Amherstview studio or arrange a mobile visit.
                                                                                                                          Tuesday through Saturday regular hours. Sunday and Monday available at a competitive premium fee.
                                                                                                                                  </p>
                                                                                                                                          <div className="flex flex-wrap gap-4 justify-center mb-10">
                                                                                                                                                    <a href="https://square.site/book/EMLYSALON" target="_blank" rel="noopener noreferrer" className="btn-cta">
                                                                                                                                                                Book Online
                                                                                                                                                                          </a>
                                                                                                                                                                                    <a href="tel:6139298711" className="btn-outline">
                                                                                                                                                                                                (613) 929-8711
                                                                                                                                                                                                          </a>
                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                          <div className="glass-purple rounded-2xl p-8 animate-pulse-glow">
                                                                                                                                                                                                                                    <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full mb-5" style={{ background: 'rgba(139,60,247,0.15)', border: '1px solid rgba(139,60,247,0.30)' }}>
                                                                                                                                                                                                                                                <span className="w-2 h-2 rounded-full animate-pulse" style={{ background: '#8b3cf7' }} />
                                                                                                                                                                                                                                                            <span className="text-xs tracking-widest uppercase font-semibold" style={{ color: '#a855f7' }}>Coming Soon</span>
                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                <h3 className="text-xl font-bold mb-3" style={{ color: '#f0eaf8' }}>Dedicated Home Salon</h3>
                                                                                                                                                                                                                                                                                          <p className="text-base leading-relaxed max-w-md mx-auto" style={{ color: '#a9a3b8' }}>
                                                                                                                                                                                                                                                                                                      Emily is crafting a bespoke private home salon — an intimate, beautifully designed space built exclusively for the elevated hair-care experience you deserve.
                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                          <p className="text-xs tracking-widest uppercase mt-4 font-semibold" style={{ color: '#8b3cf7' }}>
                                                                                                                                                                                                                                                                                                                                      Stay Tuned
                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                  </section>
                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                    }