import React from 'react';

const standardDays = [
      { day: 'Tuesday',   hours: '9:00 am – 6:00 pm' },
        { day: 'Wednesday', hours: '9:00 am – 6:00 pm' },
          { day: 'Thursday',  hours: '9:00 am – 6:00 pm' },
            { day: 'Friday',    hours: '9:00 am – 6:00 pm' },
              { day: 'Saturday',  hours: '9:00 am – 4:00 pm' },
              ];

              export default function HoursSection() {
                return (
                    <section id="hours" className="py-24 px-6">
                          <div className="max-w-3xl mx-auto text-center">
                                  <p className="text-xs tracking-widest uppercase mb-4 font-semibold" style={{ color: '#14b8a6' }}>
                                            Availability
                                                    </p>
                                                            <h2 className="font-black mb-4" style={{ fontSize: 'clamp(28px,4vw,48px)', color: '#f0eaf8' }}>
                                                                      Hours &amp; Booking
                                                                              </h2>
                                                                                      <hr className="divider-brand" />

                                                                                              <div className="mt-10 glass rounded-2xl p-8 text-left">
                                                                                                        <p className="text-xs tracking-widest uppercase font-semibold text-center mb-6" style={{ color: '#a855f7' }}>
                                                                                                                    Standard Hours — Amherstview Studio
                                                                                                                              </p>
                                                                                                                                        <ul className="space-y-4">
                                                                                                                                                    {standardDays.map(({ day, hours }) => (
                                                                                                                                                                  <li key={day} className="flex items-center justify-between pb-3" style={{ borderBottom: '1px solid #3b3a52' }}>
                                                                                                                                                                                  <span className="text-sm font-semibold tracking-wide" style={{ color: '#f0eaf8' }}>{day}</span>
                                                                                                                                                                                                  <span className="text-base" style={{ color: '#a9a3b8' }}>{hours}</span>
                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                      </ul>
                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                className="mt-6 relative rounded-2xl p-8 backdrop-blur-sm overflow-hidden"
                                                                                                                                                                                                                                                                          style={{ border: '1px solid rgba(13,148,136,0.40)', background: 'rgba(13,148,136,0.05)', boxShadow: '0 0 20px 2px rgba(13,148,136,0.20)' }}
                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                            <div aria-hidden="true" className="pointer-events-none absolute -top-8 -right-8 w-40 h-40 rounded-full blur-3xl" style={{ background: 'rgba(13,148,136,0.15)' }} />
                                                                                                                                                                                                                                                                                                      <div className="relative flex flex-col sm:flex-row items-center gap-4 text-left">
                                                                                                                                                                                                                                                                                                                  <div className="flex-shrink-0 w-12 h-12 rounded-full flex items-center justify-center text-xl" style={{ background: 'rgba(13,148,136,0.15)', border: '1px solid rgba(13,148,136,0.30)' }}>
                                                                                                                                                                                                                                                                                                                                ◈
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                      <p className="text-xs tracking-widest uppercase font-semibold mb-1" style={{ color: '#0d9488' }}>
                                                                                                                                                                                                                                                                                                                                                                                      Sunday &amp; Monday — Premium Availability
                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-base leading-relaxed" style={{ color: '#a9a3b8' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                  Sunday and Monday appointments are available at a{' '}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <strong style={{ color: '#14b8a6' }}>competitive premium fee</strong>.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Perfect for clients who need flexibility outside standard hours.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="mt-5 text-sm italic" style={{ color: 'rgba(169,163,184,0.60)' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Sunday &amp; Monday bookings are by request — contact Emily directly to arrange.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }