import React from 'react';

const cards = [
  {
      icon: '🏠',
          title: 'In-Home Visits',
              desc: 'Full salon experience in the comfort of your own home. Cuts, colour, and treatments professionally executed with no compromise on quality.',
                  tags: ['Flexible scheduling', 'Amherstview & surrounding area'],
                      featured: false,
                          cta: 'Book a Home Visit',
                            },
                              {
                                  icon: '💝',
                                      title: 'Retirement Home Visits',
                                          desc: 'Dedicated, compassionate mobile visits to retirement residences and care facilities. Patient, unhurried, and fully equipped — because everyone deserves to feel their best.',
                                              tags: ['Serving Amherstview area communities', 'Gentle, specialized care'],
                                                  featured: true,
                                                      cta: 'Schedule a Visit',
                                                        },
                                                          {
                                                              icon: '🎉',
                                                                  title: 'Special Occasions',
                                                                      desc: 'On-site styling for bridal parties, milestone celebrations, and special events. Elevate every occasion with expert artistry.',
                                                                          tags: ['Bridal & events', 'Group bookings welcome'],
                                                                              featured: false,
                                                                                  cta: 'Enquire Now',
                                                                                    },
                                                                                    ];

                                                                                    export default function MobileConcierge() {
                                                                                      return (
                                                                                          <section
                                                                                                id="mobile"
                                                                                                      className="py-24 px-6"
                                                                                                            style={{ background: 'radial-gradient(ellipse at center, rgba(139,60,247,0.06) 0%, transparent 70%)' }}
                                                                                                                >
                                                                                                                      <div className="text-center max-w-2xl mx-auto mb-16">
                                                                                                                              <span
                                                                                                                                        className="inline-block px-5 py-2 rounded-full text-xs tracking-widest uppercase font-semibold mb-6"
                                                                                                                                                  style={{ border: '1px solid rgba(139,60,247,0.30)', background: 'rgba(139,60,247,0.08)', color: '#a855f7' }}
                                                                                                                                                          >
                                                                                                                                                                    Mobile Concierge
                                                                                                                                                                            </span>
                                                                                                                                                                                    <h2 className="font-black mb-4" style={{ fontSize: 'clamp(32px,5vw,56px)', color: '#f0eaf8' }}>
                                                                                                                                                                                              The Salon Comes{' '}
                                                                                                                                                                                                        <span style={{ background: 'linear-gradient(135deg,#8b3cf7,#0d9488)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' }}>
                                                                                                                                                                                                                    To You
                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                      </h2>
                                                                                                                                                                                                                                              <hr className="divider-brand" />
                                                                                                                                                                                                                                                      <p className="text-lg mt-4 leading-relaxed" style={{ color: '#a9a3b8' }}>
                                                                                                                                                                                                                                                                Luxury hair services delivered to your home, retirement residence, or event venue.
                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                    <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-5xl mx-auto">
                                                                                                                                                                                                                                                                                            {cards.map((card) => (
                                                                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                                                                  key={card.title}
                                                                                                                                                                                                                                                                                                                              className="relative flex flex-col rounded-2xl p-8 backdrop-blur-sm transition-all duration-300"
                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                        background: '#27273a',
                                                                                                                                                                                                                                                                                                                                                                      border: card.featured ? '1px solid rgba(139,60,247,0.50)' : '1px solid #3b3a52',
                                                                                                                                                                                                                                                                                                                                                                                    boxShadow: card.featured ? '0 0 20px 2px rgba(139,60,247,0.35)' : 'none',
                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                      {card.featured && (
                                                                                                                                                                                                                                                                                                                                                                                                                                    <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="absolute -top-3 right-4 px-3 py-1 rounded-full text-xs tracking-widest uppercase font-semibold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{ background: 'rgba(139,60,247,0.15)', border: '1px solid rgba(139,60,247,0.40)', color: '#a855f7' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Specialized Care
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="text-4xl mb-5">{card.icon}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3 className="text-lg font-bold mb-3" style={{ color: '#f0eaf8' }}>{card.title}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-base leading-relaxed mb-5" style={{ color: '#a9a3b8' }}>{card.desc}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex flex-wrap gap-2 mb-6 mt-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {card.tags.map((tag) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span key={tag} className="text-xs px-3 py-1 rounded-full" style={{ background: 'rgba(13,148,136,0.10)', border: '1px solid rgba(13,148,136,0.30)', color: '#14b8a6' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {tag}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                href="tel:6139298711"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="text-center text-xs tracking-widest uppercase py-3 px-6 rounded-lg transition-all duration-200 font-semibold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={card.featured ? { background: '#8b3cf7', color: '#fff' } : { border: '1px solid rgba(139,60,247,0.40)', color: '#a855f7' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {card.cta}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }