'use client';
import React, { useState, useEffect } from 'react';

export default function Navigation() {
  const [scrolled, setScrolled] = useState(false);

    useEffect(() => {
        const handleScroll = () => setScrolled(window.scrollY > 50);
            window.addEventListener('scroll', handleScroll, { passive: true });
                return () => window.removeEventListener('scroll', handleScroll);
                  }, []);

                    return (
                        <nav
                              className={[
                                      'fixed top-0 left-0 right-0 z-50 flex items-center justify-between px-8 py-4 transition-all duration-300',
                                              scrolled ? 'bg-charcoal/95 backdrop-blur-xl border-b border-border' : 'bg-transparent',
                                                    ].join(' ')}
                                                        >
                                                              <a href="#" className="text-base tracking-widest uppercase font-semibold" style={{ color: '#f0eaf8' }}>
                                                                      The Perfect Look <span style={{ color: '#a855f7' }}>By Emily</span>
                                                                            </a>
                                                                                  <div className="hidden md:flex items-center gap-8">
                                                                                          {[
                                                                                                    { label: 'About', href: '#about' },
                                                                                                              { label: 'Services', href: '#services' },
                                                                                                                        { label: 'Mobile', href: '#mobile' },
                                                                                                                                  { label: 'Hours', href: '#hours' },
                                                                                                                                          ].map(({ label, href }) => (
                                                                                                                                                    <a key={label} href={href} className="text-xs tracking-widest uppercase transition-colors" style={{ color: '#a9a3b8' }}>
                                                                                                                                                                {label}
                                                                                                                                                                          </a>
                                                                                                                                                                                  ))}
                                                                                                                                                                                          <a href="tel:6139298711" className="text-xs tracking-wider font-semibold" style={{ color: '#14b8a6' }}>
                                                                                                                                                                                                    (613) 929-8711
                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                    <a
                                                                                                                                                                                                                              href="https://square.site/book/EMLYSALON"
                                                                                                                                                                                                                                        target="_blank"
                                                                                                                                                                                                                                                  rel="noopener noreferrer"
                                                                                                                                                                                                                                                            className="btn-cta"
                                                                                                                                                                                                                                                                      style={{ padding: '0.6rem 1.4rem', fontSize: '0.75rem' }}
                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                        Book Now
                                                                                                                                                                                                                                                                                                </a>
                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                            <div className="flex md:hidden items-center gap-3">
                                                                                                                                                                                                                                                                                                                    <a href="tel:6139298711" className="text-xs tracking-wider" style={{ color: '#14b8a6' }}>
                                                                                                                                                                                                                                                                                                                              (613) 929-8711
                                                                                                                                                                                                                                                                                                                                      </a>
                                                                                                                                                                                                                                                                                                                                              <a
                                                                                                                                                                                                                                                                                                                                                        href="https://square.site/book/EMLYSALON"
                                                                                                                                                                                                                                                                                                                                                                  target="_blank"
                                                                                                                                                                                                                                                                                                                                                                            rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                      className="btn-cta"
                                                                                                                                                                                                                                                                                                                                                                                                style={{ padding: '0.5rem 1rem', fontSize: '0.7rem' }}
                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                  Book
                                                                                                                                                                                                                                                                                                                                                                                                                          </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                    </nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                      }