import React from 'react';

const pillars = [
  {
      id: 'studio',
          icon: '✦',
              eyebrow: 'Amherstview Studio',
                  title: 'Premium Chair Experience',
                      description: 'Emily works from a beautifully appointed rented chair at a premium Amherstview studio. Every session is one-on-one — no rushing, no sharing, just focused artistry.',
                          services: [
                                { name: 'Balayage & Colour Melt', price: 'from $185' },
                                      { name: 'Colour Correction', price: 'from $250' },
                                            { name: 'Colour Gloss', price: 'from $95' },
                                                  { name: "Women's Cut & Style", price: 'from $65' },
                                                        { name: 'Deep Conditioning / Olaplex', price: 'from $45' },
                                                            ],
                                                                accentLight: '#a855f7',
                                                                    borderColor: 'rgba(139,60,247,0.40)',
                                                                        featured: true,
                                                                          },
                                                                            {
                                                                                id: 'mobile',
                                                                                    icon: '🚗',
                                                                                        eyebrow: 'Mobile Care',
                                                                                            title: 'We Come to You',
                                                                                                description: 'Emily travels to retirement homes, long-term care facilities, and private residences across the Amherstview area. Compassionate, fully equipped, and unhurried.',
                                                                                                    services: [
                                                                                                          { name: 'In-Home Cut & Style', price: 'from $75' },
                                                                                                                { name: 'Retirement Home Visit', price: 'from $75' },
                                                                                                                      { name: 'In-Home Colour', price: 'from $120' },
                                                                                                                            { name: 'Flexible Scheduling', price: 'By request' },
                                                                                                                                ],
                                                                                                                                    accentLight: '#14b8a6',
                                                                                                                                        borderColor: 'rgba(13,148,136,0.40)',
                                                                                                                                            featured: false,
                                                                                                                                              },
                                                                                                                                                {
                                                                                                                                                    id: 'trending',
                                                                                                                                                        icon: '◈',
                                                                                                                                                            eyebrow: 'Trending Recommendations',
                                                                                                                                                                title: 'Personalized Modern Style',
                                                                                                                                                                    description: "Emily stays at the forefront of industry trends. During your consultation she curates a look that's contemporary, flattering, and uniquely yours.",
                                                                                                                                                                        services: [
                                                                                                                                                                              { name: 'Dimensional Balayage', price: 'from $185' },
                                                                                                                                                                                    { name: 'Bespoke Textured Cut', price: 'from $75' },
                                                                                                                                                                                          { name: 'Toning & Glossing Refresh', price: 'from $85' },
                                                                                                                                                                                                { name: 'Style Consultation', price: 'Complimentary' },
                                                                                                                                                                                                    ],
                                                                                                                                                                                                        accentLight: '#a855f7',
                                                                                                                                                                                                            borderColor: 'rgba(139,60,247,0.40)',
                                                                                                                                                                                                                featured: false,
                                                                                                                                                                                                                  },
                                                                                                                                                                                                                  ];

                                                                                                                                                                                                                  export default function ServicesMatrix() {
                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                        <section id="services" className="py-24 px-6">
                                                                                                                                                                                                                              <div className="text-center max-w-2xl mx-auto mb-16">
                                                                                                                                                                                                                                      <p className="text-xs tracking-widest uppercase mb-4 font-semibold" style={{ color: '#14b8a6' }}>
                                                                                                                                                                                                                                                What We Offer
                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                <h2 className="font-black mb-4" style={{ fontSize: 'clamp(32px,5vw,56px)', color: '#f0eaf8' }}>
                                                                                                                                                                                                                                                                          Services &amp; Pricing
                                                                                                                                                                                                                                                                                  </h2>
                                                                                                                                                                                                                                                                                          <hr className="divider-brand" />
                                                                                                                                                                                                                                                                                                  <p className="text-lg mt-4 leading-relaxed" style={{ color: '#a9a3b8' }}>
                                                                                                                                                                                                                                                                                                            Goldwell-certified colour expertise, at the studio or on your doorstep.
                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-6xl mx-auto">
                                                                                                                                                                                                                                                                                                                                        {pillars.map((p) => (
                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                              key={p.id}
                                                                                                                                                                                                                                                                                                                                                                          className="relative flex flex-col rounded-2xl p-8 backdrop-blur-sm transition-all duration-300"
                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                    background: '#27273a',
                                                                                                                                                                                                                                                                                                                                                                                                                  border: `1px solid ${p.borderColor}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                boxShadow: p.featured ? `0 0 20px 2px rgba(139,60,247,0.35)` : 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {p.featured && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="absolute -top-3 left-1/2 -translate-x-1/2 px-4 py-1 rounded-full text-xs tracking-widest uppercase font-semibold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{ background: 'rgba(139,60,247,0.15)', border: '1px solid rgba(139,60,247,0.40)', color: '#a855f7' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Studio Flagship
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex items-center gap-3 mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-2xl" style={{ color: p.accentLight }}>{p.icon}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="text-xs tracking-widest uppercase font-semibold" style={{ color: p.accentLight }}>{p.eyebrow}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3 className="text-xl font-bold mb-3" style={{ color: '#f0eaf8' }}>{p.title}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-base leading-relaxed mb-6" style={{ color: '#a9a3b8' }}>{p.description}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <ul className="mt-auto space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {p.services.map((svc) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <li key={svc.name} className="flex items-center justify-between pb-2" style={{ borderBottom: '1px solid #3b3a52' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="text-sm" style={{ color: 'rgba(240,234,248,0.80)' }}>{svc.name}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-xs font-bold" style={{ color: p.accentLight }}>{svc.price}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      href="https://square.site/book/EMLYSALON"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="mt-8 text-center text-xs tracking-widest uppercase py-3 px-6 rounded-lg transition-all duration-200 font-semibold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{ border: `1px solid ${p.borderColor}`, color: p.accentLight }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Book This Service
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }