import HeroSection from '@/components/HeroSection';
import ServicesCard from '@/components/ServicesCard';
import BookingSection from '@/components/BookingSection';
import Navigation from '@/components/Navigation';

export default function Home() {
  return (
      <div className="flex flex-col min-h-screen bg-[#0f0a1a]">
            <Navigation />
                  <main className="flex-grow">
                          <HeroSection />
                                  <section id="services" className="container mx-auto px-4 py-24">
                                            <div className="text-center mb-16">
                                                        <span className="text-[#14b8a6] font-bold tracking-widest uppercase text-sm">What Emily Offers</span>
                                                                    <h2 className="text-4xl font-serif text-white mt-3 mb-4">Premium Services</h2>
                                                                                <p className="text-gray-400 max-w-2xl mx-auto">Utilizing Goldwell products and CLICS AI technology for precision colour mixology.</p>
                                                                                          </div>
                                                                                                    <ServicesCard />
                                                                                                            </section>
                                                                                                                    <section id="booking" className="container mx-auto px-4 py-24">
                                                                                                                              <div className="text-center mb-16">
                                                                                                                                          <span className="text-[#14b8a6] font-bold tracking-widest uppercase text-sm">Secure Your Spot</span>
                                                                                                                                                      <h2 className="text-4xl font-serif text-white mt-3 mb-4">Book Your Appointment</h2>
                                                                                                                                                                  <p className="text-gray-400 max-w-2xl mx-auto">Available Tuesday–Saturday in Amherstview. Premium Sunday & Monday mobile visits available.</p>
                                                                                                                                                                            </div>
                                                                                                                                                                                      <BookingSection />
                                                                                                                                                                                              </section>
                                                                                                                                                                                                      <section className="py-24 relative overflow-hidden">
                                                                                                                                                                                                                <div className="absolute inset-0 bg-gradient-to-b from-transparent via-[#8b5cf6]/5 to-transparent" />
                                                                                                                                                                                                                          <div className="container mx-auto px-4 text-center relative z-10">
                                                                                                                                                                                                                                      <div className="glass-panel-dark rounded-3xl p-12 max-w-3xl mx-auto">
                                                                                                                                                                                                                                                    <span className="text-[#14b8a6] font-bold tracking-widest uppercase text-sm">Coming Soon</span>
                                                                                                                                                                                                                                                                  <h2 className="text-4xl md:text-5xl font-serif text-white mt-4 mb-6">The Aurora Studio</h2>
                                                                                                                                                                                                                                                                                <p className="text-gray-300 text-lg leading-relaxed mb-8">A fully customized, ultra-high-end home salon in a converted double-car garage. Smart mirrors, AR hair preview, IoT Goldwell CLICS dispensers, and a breathtaking dark glassmorphic aesthetic. The future of luxury styling.</p>
                                                                                                                                                                                                                                                                                              <div className="bg-gradient-to-r from-[#8b5cf6] to-[#14b8a6] p-[1px] rounded-full inline-block">
                                                                                                                                                                                                                                                                                                              <div className="bg-[#0f0a1a] px-8 py-3 rounded-full">
                                                                                                                                                                                                                                                                                                                                <span className="font-semibold text-white tracking-wide">Stay tuned for the grand reveal</span>
                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                            </section>
                                                                                                                                                                                                                                                                                                                                                                                                  </main>
                                                                                                                                                                                                                                                                                                                                                                                                        <footer className="glass-nav py-8">
                                                                                                                                                                                                                                                                                                                                                                                                                <div className="container mx-auto px-4 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-[#14b8a6] font-serif text-xl mb-2">The Perfect Look By Emily</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-gray-400 text-sm">Odessa · Amherstview · Kingston, Ontario | (613) 583-9977</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-gray-600 text-xs mt-4">© {new Date().getFullYear()} The Perfect Look By Emily. All rights reserved.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }