import React from 'react';
export default function BookingSection() {
    return React.createElement('div', null);
}'use client';
import { useState } from 'react';
import { Calendar, Phone, MapPin, Home } from 'lucide-react';

export default function BookingSection() {
  const [serviceType, setServiceType] = useState<'salon' | 'mobile'>('salon');

    return (
        <div className="max-w-4xl mx-auto">
              <div className="glass-panel-dark rounded-3xl p-8 md:p-12">
                      {/* Service Type Toggle */}
                              <div className="flex gap-4 mb-10 p-1 bg-white/5 rounded-2xl">
                                        <button
                                                    onClick={() => setServiceType('salon')}
                                                                className={`flex-1 flex items-center justify-center gap-2 py-3 px-6 rounded-xl font-semibold text-sm transition-all ${serviceType === 'salon' ? 'bg-[#8b5cf6] text-white shadow-lg shadow-[#8b5cf6]/30' : 'text-gray-400 hover:text-white'}`}>
                                                                            <MapPin className="w-4 h-4" /> Amherstview Salon Chair
                                                                                      </button>
                                                                                                <button
                                                                                                            onClick={() => setServiceType('mobile')}
                                                                                                                        className={`flex-1 flex items-center justify-center gap-2 py-3 px-6 rounded-xl font-semibold text-sm transition-all ${serviceType === 'mobile' ? 'bg-[#14b8a6] text-white shadow-lg shadow-[#14b8a6]/30' : 'text-gray-400 hover:text-white'}`}>
                                                                                                                                    <Home className="w-4 h-4" /> Mobile / Home Visit
                                                                                                                                              </button>
                                                                                                                                                      </div>

                                                                                                                                                              {/* Booking Info */}
                                                                                                                                                                      <div className="grid md:grid-cols-2 gap-8 mb-10">
                                                                                                                                                                                <div>
                                                                                                                                                                                            <h3 className="text-2xl font-serif text-white mb-4">
                                                                                                                                                                                                          {serviceType === 'salon' ? 'Amherstview Salon' : 'Mobile Service'}
                                                                                                                                                                                                                      </h3>
                                                                                                                                                                                                                                  <p className="text-gray-400 leading-relaxed mb-6">
                                                                                                                                                                                                                                                {serviceType === 'salon'
                                                                                                                                                                                                                                                                ? 'Professional salon chair environment in Amherstview. Tuesday–Saturday. Perfect for complex colour services, balayage & corrections.'
                                                                                                                                                                                                                                                                                : 'Emily comes directly to you — home, retirement community, or office. Available across Kingston, Odessa & surrounding areas.'}
                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                        <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                      <div className="flex items-center gap-3 text-sm text-gray-300">
                                                                                                                                                                                                                                                                                                                                      <Calendar className="w-4 h-4 text-[#8b5cf6]" />
                                                                                                                                                                                                                                                                                                                                                      <span>{serviceType === 'salon' ? 'Tue–Sat (premium Sun & Mon available)' : 'Available 7 days including evenings'}</span>
                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex items-center gap-3 text-sm text-gray-300">
                                                                                                                                                                                                                                                                                                                                                                                                  <Phone className="w-4 h-4 text-[#14b8a6]" />
                                                                                                                                                                                                                                                                                                                                                                                                                  <span>(613) 583-9977</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex items-center gap-3 text-sm text-gray-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <MapPin className="w-4 h-4 text-[#8b5cf6]" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span>{serviceType === 'salon' ? 'Amherstview, ON' : 'Kingston, Odessa & surrounding areas'}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Square Booking CTA */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex flex-col justify-center gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="bg-white/5 rounded-2xl p-6 border border-white/10">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-[#14b8a6] text-xs font-bold uppercase tracking-wider mb-2">Powered by Square Appointments</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-white font-serif text-xl mb-4">Book Instantly Online</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            href="https://square.site/book/EMLYSALON"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="btn-primary block text-center mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Book on Square
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-gray-500 text-xs text-center">Secure payment · Instant confirmation · HST included</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a href="tel:6135839977" className="btn-teal text-center flex items-center justify-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Phone className="w-4 h-4" /> Call to Book: (613) 583-9977
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* HST Notice */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="border-t border-white/10 pt-6 flex items-start gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="w-2 h-2 rounded-full bg-[#14b8a6] mt-1.5 flex-shrink-0" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-gray-500 text-xs leading-relaxed">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            All prices are subject to 13% Ontario HST where applicable. Deposits may be required for colour services over 2 hours.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Cancellations require 24-hour notice.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
